### PR TITLE
Add option to copy attributes from existing model to generator

### PR DESCRIPTION
**Pull request by fny**
I don't think I was clear in #240. That was not the use case I intend.  (`--copy` is perhaps a misleading name for the flag.)

Currently, given an existing model without a fabricator, only an empty fabricator would be generated for that model using the provided generator.  Say we have a `User` model with string field `name`,  `rails g fabrication:model User` would create the following:

```ruby
Fabricator(:user) do
end
```

This pull request will allow for attributes to be copied from the provided model:  `rails g fabrication:model User --copy`

```ruby
Fabricator(:user) do
  id         1
  name       'MyString'
  created_at '2015-01-25'
  updated_at '2015-01-25'
end
```

This comes extremely handy when migrating to fabricators from fixtures or adding fabricators for models that never had a fabricator generated to begin with.

Note this implementation only handles ActiveRecord models.

### CODE REVIEW

**Comment by paulelliott** [comment]
Oh, cool. I misunderstood what you were talking about before.

This looks cool although I'm not sure about the interface for it. Could we just do it all the time and ignore it whenever a model can't be identified?

**Comment by fny** [comment]
I'd prefer that behavior too. I can clean this up tonight and perhaps figure a way to add Mongoid support too. Basically, when no attributes are provided, the generator should look for a corresponding model and use its attributes if possible.

**Comment by paulelliott** [comment]
Exactly. Thanks for working on this!

**Comment by fny** [comment]
Do you mind if I rename `templates/fabricator.rb` to `templates/fabricator.erb`?

**Comment by paulelliott** [comment]
Go for it.

On Thursday, January 29, 2015, Faraz Yashar <notifications@github.com>
wrote:

> Do you mind if I rename templates/fabricator.rb to
> templates/fabricator.erb?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/paulelliott/fabrication/pull/241#issuecomment-72140970>
> .
>


-- 
Paul

**Comment by fny** [comment]
So here's the working version for AR. Do you think it would be a good idea to skip the id and timestamp fields?

I can give Mongoid a shot, but it's a bit more of a project to support it and guarantee stability... There'd need to be something maintained that maps classes (e.g. `Mongoid::Boolean`) to strings understood by `Rails::Generators::GeneratedAttribute.new`.

**Comment by fny** [comment]
Bump.

lonely

**Pull request merged**
